export {
  parseAutomationCommand,
  parseClaudeAutomationCommand,
  type ClaudeAutomationCommand,
  type GoalAutomationCommand,
  type LoopAutomationCommand,
} from './automation-command.parser.js';

export {
  NativeClaudeAutomationError,
  NativeClaudeAutomationRunner,
  buildClaudeAutomationPreferenceArgs,
  buildGoalClearClaudeArgs,
  buildGoalClaudeArgs,
  buildLoopClaudeArgs,
  createTmuxSessionName,
  parseClaudeVersion,
  validateClaudeLoopInput,
  type ClaudeAutomationCliPreferences,
  type ClaudeAutomationSessionTarget,
  type ExecFileResult,
  type NativeClaudeAutomationDependencies,
  type NativeClaudeAutomationStartOptions,
  type NativeClaudeGoalCallbacks,
  type NativeClaudeGoalCleanupResult,
  type NativeClaudeGoalCleanupStatus,
  type NativeClaudeGoalClearOptions,
  type NativeClaudeGoalClearResult,
  type NativeClaudeGoalExit,
  type NativeClaudeGoalHandle,
  type NativeClaudeLoopHandle,
  type NativeClaudeLoopObservation,
  type NativeClaudeProcessSnapshot,
  type NativeClaudeRawEvent,
  type NativeClaudeResultSummary,
} from './native-claude-automation.runner.js';

export {
  ClaudeAutomationService,
  ClaudeAutomationServiceError,
  MAX_AUTOMATION_CORRELATION_ID_LENGTH,
  resolveGoalClearOptionsForSession,
  toClaudeAutomationSnapshot,
  type ClaudeGoalClearSession,
  type ClaudeAutomationGoalCallbacks,
  type ClaudeAutomationRepository,
  type ClaudeAutomationRunner,
  type ClaudeAutomationServiceDependencies,
  type ClaudeAutomationServiceErrorCode,
  type ClaudeAutomationServiceSnapshot,
  type ClaudeAutomationStartInput,
  type ClaudeAutomationStateListener,
} from './claude-automation.service.js';
